syntax = "proto3";

package kv.v1;

option go_package = "github.com/kirillidk/distributed-kv-storage/api/gen/go/kv/v1;kvv1";

service KVService {
  rpc Set(SetRequest) returns (SetResponse);
  rpc Get(GetRequest) returns (GetResponse);
}

message SetRequest {
  // Must not be empty
  bytes key = 1;

  // May be empty
  bytes value = 2;

  // Expiration in seconds. Zero means no expiration; values up to 30 days
  // are relative, while larger values are Unix timestamps
  uint64 ttl = 3;
}

message SetResponse {}

message GetRequest {
  // Must not be empty
  bytes key = 1;
}

message GetResponse {
  bytes value = 1;
  uint64 expires_at = 2;
}
